### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by JingShan666** [Cuieney/vld#4]
在手机上运行一下，app打不开，我看了下后台，报ClassNotFound错误，指向MainActivity这个类，大神能指教一下吗？

**Comment by Cuieney** [comment]
大兄弟，刚刚我试出了这个问题，第一次build install app的时候会出现这个问题，但是你再次make project的时候就好了，目前我也没搞清楚啥问题。我查查资料看看啥原因 @JingShan666

**Comment by gaodengjiaoyu** [comment]
大兄弟，你好，项目看起来很好，学习了。只是 第一次运行报这个错误
06-14 09:08:10.317 12374-12374/org.cuieney.videolife E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.cuieney.videolife, PID: 12374
                                                                       java.lang.RuntimeException: Unable to instantiate application org.cuieney.videolife.kotlin.App: java.lang.ClassNotFoundException: Didn't find class "org.cuieney.videolife.kotlin.App" on path: DexPathList[[zip file "/data/app/org.cuieney.videolife-2/base.apk"],nativeLibraryDirectories=[/data/app/org.cuieney.videolife-2/lib/arm, /data/app/org.cuieney.videolife-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                           at android.app.LoadedApk.makeApplication(LoadedApk.java:676)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6290)
                                                                           at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:158)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "org.cuieney.videolife.kotlin.App" on path: DexPathList[[zip file "/data/app/org.cuieney.videolife-2/base.apk"],nativeLibraryDirectories=[/data/app/org.cuieney.videolife-2/lib/arm, /data/app/org.cuieney.videolife-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                                           at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6290) 
                                                                           at android.app.ActivityThread.access$1800(ActivityThread.java:221) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:158) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                       	Suppressed: java.lang.ClassNotFoundException: org.cuieney.videolife.kotlin.App
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 12 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Cuieney** [comment]
@gaodengjiaoyu 第一次拉代码会出现这种classnotfound  再次make project 就好了 。我也没搞清楚什么情况，可能是kotlin 和java 混编导致的吧。不过还是谢谢支持。
