### ISSUE TITLE
ava.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by SnowDragon2015** [Cuieney/vld#9]
切换到Java部分的代码，可以正常运行，没问题，但是但是切换到Kotlin一直报如下错误，运行了好多次，都是这样，Rebuild Project之后也是这样
 Process: org.cuieney.videolife, PID: 22123
                                                                       java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.cuieney.videolife/org.cuieney.videolife.kotlin.ui.act.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "org.cuieney.videolife.kotlin.ui.act.MainActivity" on path: DexPathList[[zip file "/data/app/org.cuieney.videolife-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.cuieney.videolife-2, /system/lib, /system/lib/arm]]
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2116)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2335)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "org.cuieney.videolife.kotlin.ui.act.MainActivity" on path: DexPathList[[zip file "/data/app/org.cuieney.videolife-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.cuieney.videolife-2, /system/lib, /system/lib/arm]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                           at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2107)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2335) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by Cuieney** [comment]
clean rebuild 都不行？ 之前这个问题有 然后我把项目升级到3.0后 好像没有了
